--
-- XXL-JOB
-- Copyright (c) 2015-present, xuxueli.
-- Oracle 12c+
--

-- —————————————————————— job group and registry ——————————————————

CREATE TABLE xxl_job_group
(
    id           NUMBER(11)     GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    app_name     VARCHAR2(64)   NOT NULL,
    title        VARCHAR2(12)   NOT NULL,
    address_type NUMBER(4)      DEFAULT 0 NOT NULL,
    address_list VARCHAR2(4000),
    update_time  DATE,
    PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_group IS '执行器';
COMMENT ON COLUMN xxl_job_group.id IS '执行器主键ID';
COMMENT ON COLUMN xxl_job_group.app_name IS '执行器AppName';
COMMENT ON COLUMN xxl_job_group.title IS '执行器名称';
COMMENT ON COLUMN xxl_job_group.address_type IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN xxl_job_group.address_list IS '执行器地址列表，多地址逗号分隔';
COMMENT ON COLUMN xxl_job_group.update_time IS '更新时间';

CREATE TABLE xxl_job_registry
(
    id             NUMBER(11)    GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    registry_group VARCHAR2(50)  NOT NULL,
    registry_key   VARCHAR2(255) NOT NULL,
    registry_value VARCHAR2(255) NOT NULL,
    update_time    DATE,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX i_g_k_v ON xxl_job_registry (registry_group, registry_key, registry_value);

COMMENT ON TABLE xxl_job_registry IS '客户端注册';
COMMENT ON COLUMN xxl_job_registry.id IS '注册主键ID';
COMMENT ON COLUMN xxl_job_registry.registry_group IS '注册组';
COMMENT ON COLUMN xxl_job_registry.registry_key IS '注册主键';
COMMENT ON COLUMN xxl_job_registry.registry_value IS '注册值';
COMMENT ON COLUMN xxl_job_registry.update_time IS '更新时间';

-- —————————————————————— job info ——————————————————

CREATE TABLE xxl_job_info
(
    id                        NUMBER(11)     GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    job_group                 NUMBER(11)     NOT NULL,
    job_desc                  VARCHAR2(255)  NOT NULL,
    add_time                  DATE,
    update_time               DATE,
    author                    VARCHAR2(64),
    alarm_email               VARCHAR2(255),
    schedule_type             VARCHAR2(50)   DEFAULT 'NONE' NOT NULL,
    schedule_conf             VARCHAR2(128),
    misfire_strategy          VARCHAR2(50)   DEFAULT 'DO_NOTHING' NOT NULL,
    executor_route_strategy   VARCHAR2(50),
    executor_handler          VARCHAR2(255),
    executor_param            VARCHAR2(512),
    executor_block_strategy   VARCHAR2(50),
    executor_timeout          NUMBER(11)     DEFAULT 0 NOT NULL,
    executor_fail_retry_count NUMBER(11)     DEFAULT 0 NOT NULL,
    glue_type                 VARCHAR2(50)   NOT NULL,
    glue_source               CLOB,
    glue_remark               VARCHAR2(128),
    glue_updatetime           DATE,
    child_jobid               VARCHAR2(255),
    trigger_status            NUMBER(4)      DEFAULT 0 NOT NULL,
    trigger_last_time         NUMBER(20)     DEFAULT 0 NOT NULL,
    trigger_next_time         NUMBER(20)     DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_info IS '任务信息表';
COMMENT ON COLUMN xxl_job_info.id IS '任务主键ID';
COMMENT ON COLUMN xxl_job_info.job_group IS '执行器主键ID';
COMMENT ON COLUMN xxl_job_info.job_desc IS '任务描述';
COMMENT ON COLUMN xxl_job_info.add_time IS '创建时间';
COMMENT ON COLUMN xxl_job_info.update_time IS '更新时间';
COMMENT ON COLUMN xxl_job_info.author IS '作者';
COMMENT ON COLUMN xxl_job_info.alarm_email IS '报警邮件';
COMMENT ON COLUMN xxl_job_info.schedule_type IS '调度类型';
COMMENT ON COLUMN xxl_job_info.schedule_conf IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN xxl_job_info.misfire_strategy IS '调度过期策略';
COMMENT ON COLUMN xxl_job_info.executor_route_strategy IS '执行器路由策略';
COMMENT ON COLUMN xxl_job_info.executor_handler IS '执行器任务handler';
COMMENT ON COLUMN xxl_job_info.executor_param IS '执行器任务参数';
COMMENT ON COLUMN xxl_job_info.executor_block_strategy IS '阻塞处理策略';
COMMENT ON COLUMN xxl_job_info.executor_timeout IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN xxl_job_info.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN xxl_job_info.glue_type IS 'GLUE类型';
COMMENT ON COLUMN xxl_job_info.glue_source IS 'GLUE源代码';
COMMENT ON COLUMN xxl_job_info.glue_remark IS 'GLUE备注';
COMMENT ON COLUMN xxl_job_info.glue_updatetime IS 'GLUE更新时间';
COMMENT ON COLUMN xxl_job_info.child_jobid IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN xxl_job_info.trigger_status IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN xxl_job_info.trigger_last_time IS '上次调度时间';
COMMENT ON COLUMN xxl_job_info.trigger_next_time IS '下次调度时间';

CREATE TABLE xxl_job_logglue
(
    id          NUMBER(11)    GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    job_id      NUMBER(11)    NOT NULL,
    glue_type   VARCHAR2(50),
    glue_source CLOB,
    glue_remark VARCHAR2(128) NOT NULL,
    add_time    DATE,
    update_time DATE,
    PRIMARY KEY (id)
);

COMMENT ON TABLE xxl_job_logglue IS 'GLUE任务';
COMMENT ON COLUMN xxl_job_logglue.id IS 'GLUE主键ID';
COMMENT ON COLUMN xxl_job_logglue.job_id IS '任务，主键ID';
COMMENT ON COLUMN xxl_job_logglue.glue_type IS 'GLUE类型';
COMMENT ON COLUMN xxl_job_logglue.glue_source IS 'GLUE源代码';
COMMENT ON COLUMN xxl_job_logglue.glue_remark IS 'GLUE备注';
COMMENT ON COLUMN xxl_job_logglue.add_time IS '创建时间';
COMMENT ON COLUMN xxl_job_logglue.update_time IS '更新时间';

-- —————————————————————— job log and report ——————————————————

CREATE TABLE xxl_job_log
(
    id                        NUMBER(20)     GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    job_group                 NUMBER(11)     NOT NULL,
    job_id                    NUMBER(11)     NOT NULL,
    executor_address          VARCHAR2(255),
    executor_handler          VARCHAR2(255),
    executor_param            VARCHAR2(512),
    executor_sharding_param   VARCHAR2(20),
    executor_fail_retry_count NUMBER(11)     DEFAULT 0 NOT NULL,
    trigger_time              DATE,
    trigger_code              NUMBER(11)     NOT NULL,
    trigger_msg               CLOB,
    handle_time               DATE,
    handle_code               NUMBER(11)     NOT NULL,
    handle_msg                CLOB,
    alarm_status              NUMBER(4)      DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX I_trigger_time ON xxl_job_log (trigger_time);
CREATE INDEX I_handle_code ON xxl_job_log (handle_code);
CREATE INDEX I_jobid_jobgroup ON xxl_job_log (job_id, job_group);
CREATE INDEX I_job_id ON xxl_job_log (job_id);

COMMENT ON TABLE xxl_job_log IS '调度日志';
COMMENT ON COLUMN xxl_job_log.id IS '调度主键ID';
COMMENT ON COLUMN xxl_job_log.job_group IS '执行器主键ID';
COMMENT ON COLUMN xxl_job_log.job_id IS '任务，主键ID';
COMMENT ON COLUMN xxl_job_log.executor_address IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN xxl_job_log.executor_handler IS '执行器任务handler';
COMMENT ON COLUMN xxl_job_log.executor_param IS '执行器任务参数';
COMMENT ON COLUMN xxl_job_log.executor_sharding_param IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN xxl_job_log.executor_fail_retry_count IS '失败重试次数';
COMMENT ON COLUMN xxl_job_log.trigger_time IS '调度-时间';
COMMENT ON COLUMN xxl_job_log.trigger_code IS '调度-结果';
COMMENT ON COLUMN xxl_job_log.trigger_msg IS '调度-日志';
COMMENT ON COLUMN xxl_job_log.handle_time IS '执行-时间';
COMMENT ON COLUMN xxl_job_log.handle_code IS '执行-状态';
COMMENT ON COLUMN xxl_job_log.handle_msg IS '执行-日志';
COMMENT ON COLUMN xxl_job_log.alarm_status IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

CREATE TABLE xxl_job_log_report
(
    id            NUMBER(11)   GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    trigger_day   DATE,
    running_count NUMBER(11)   DEFAULT 0 NOT NULL,
    suc_count     NUMBER(11)   DEFAULT 0 NOT NULL,
    fail_count    NUMBER(11)   DEFAULT 0 NOT NULL,
    update_time   DATE,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX i_trigger_day ON xxl_job_log_report (trigger_day);

COMMENT ON TABLE xxl_job_log_report IS '调度报告';
COMMENT ON COLUMN xxl_job_log_report.id IS '调度报告主键ID';
COMMENT ON COLUMN xxl_job_log_report.trigger_day IS '调度-时间';
COMMENT ON COLUMN xxl_job_log_report.running_count IS '运行中-日志数量';
COMMENT ON COLUMN xxl_job_log_report.suc_count IS '执行成功-日志数量';
COMMENT ON COLUMN xxl_job_log_report.fail_count IS '执行失败-日志数量';
COMMENT ON COLUMN xxl_job_log_report.update_time IS '更新时间';

-- —————————————————————— lock ——————————————————

CREATE TABLE xxl_job_lock
(
    lock_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY (lock_name)
);

COMMENT ON TABLE xxl_job_lock IS '并发锁';
COMMENT ON COLUMN xxl_job_lock.lock_name IS '锁名称';

-- —————————————————————— user ——————————————————

CREATE TABLE xxl_job_user
(
    id         NUMBER(11)    GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    username   VARCHAR2(50)  NOT NULL,
    password   VARCHAR2(100) NOT NULL,
    token      VARCHAR2(100),
    role       NUMBER(4)     NOT NULL,
    permission VARCHAR2(255),
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX i_username ON xxl_job_user (username);

COMMENT ON TABLE xxl_job_user IS '用户账号';
COMMENT ON COLUMN xxl_job_user.id IS '用户主键ID';
COMMENT ON COLUMN xxl_job_user.username IS '账号';
COMMENT ON COLUMN xxl_job_user.password IS '密码加密信息';
COMMENT ON COLUMN xxl_job_user.token IS '登录token';
COMMENT ON COLUMN xxl_job_user.role IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN xxl_job_user.permission IS '权限：执行器ID列表，多个逗号分割';

-- —————————————————————— for default data ——————————————————

INSERT INTO xxl_job_group(id, app_name, title, address_type, address_list, update_time)
VALUES (1, 'xxl-job-executor-sample', '通用执行器Sample', 0, NULL, SYSDATE);
INSERT INTO xxl_job_group(id, app_name, title, address_type, address_list, update_time)
VALUES (2, 'xxl-job-executor-sample-ai', 'AI执行器Sample', 0, NULL, SYSDATE);

INSERT INTO xxl_job_info(id, job_group, job_desc, add_time, update_time, author, alarm_email,
                         schedule_type, schedule_conf, misfire_strategy, executor_route_strategy,
                         executor_handler, executor_param, executor_block_strategy, executor_timeout,
                         executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime,
                         child_jobid)
VALUES (1, 1, '示例任务01', SYSDATE, SYSDATE, 'XXL', '', 'CRON', '0 0 0 * * ? *',
        'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        SYSDATE, '');
INSERT INTO xxl_job_info(id, job_group, job_desc, add_time, update_time, author, alarm_email,
                         schedule_type, schedule_conf, misfire_strategy, executor_route_strategy,
                         executor_handler, executor_param, executor_block_strategy, executor_timeout,
                         executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime,
                         child_jobid)
VALUES (2, 2, 'Ollama示例任务01', SYSDATE, SYSDATE, 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'ollamaJobHandler', '{
    "input": "慢SQL问题分析思路",
    "prompt": "你是一个研发工程师，擅长解决技术类问题。",
    "model": "qwen3:0.6b"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        SYSDATE, '');
INSERT INTO xxl_job_info(id, job_group, job_desc, add_time, update_time, author, alarm_email,
                         schedule_type, schedule_conf, misfire_strategy, executor_route_strategy,
                         executor_handler, executor_param, executor_block_strategy, executor_timeout,
                         executor_fail_retry_count, glue_type, glue_source, glue_remark, glue_updatetime,
                         child_jobid)
VALUES (3, 2, 'Dify示例任务', SYSDATE, SYSDATE, 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'difyWorkflowJobHandler', '{
    "inputs":{
        "input":"查询班级各学科前三名"
    },
    "user": "xxl-job",
    "baseUrl": "http://localhost/v1",
    "apiKey": "app-OUVgNUOQRIMokfmuJvBJoUTN"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        SYSDATE, '');

INSERT INTO xxl_job_user(id, username, password, role, permission)
VALUES (1, 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1, NULL);

INSERT INTO xxl_job_lock (lock_name)
VALUES ('schedule_lock');

COMMIT;